from time import sleep

SLEEP_TIME = 0.05


def chemin_1():
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |        *          |               ')
    sleep(SLEEP_TIME)
    print('             |       *           |               ')
    sleep(SLEEP_TIME)
    print('             |      *            |               ')
    sleep(SLEEP_TIME)
    print('             |     *             |               ')
    sleep(SLEEP_TIME)
    print('             |      *            |               ')
    sleep(SLEEP_TIME)
    print('             |       *           |               ')
    sleep(SLEEP_TIME)
    print('             \        *          /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /     *         \                 ')
    sleep(SLEEP_TIME)
    print('              /     *           \                ')
    sleep(SLEEP_TIME)
    print('             /     *             \               ')
    sleep(SLEEP_TIME)
    print('             \    *              /               ')
    sleep(SLEEP_TIME)
    print('              \  *              /                ')
    sleep(SLEEP_TIME)
    print('               \*              /                 ')
    sleep(SLEEP_TIME)
    print('               /  *            \                 ')
    sleep(SLEEP_TIME)
    print('              /    *            \                ')
    sleep(SLEEP_TIME)
    print('             /      *            \               ')
    sleep(SLEEP_TIME)
    print('             \       *           /               ')
    sleep(SLEEP_TIME)
    print('              \       *         /                ')
    sleep(SLEEP_TIME)
    print('               \       *       /                 ')
    sleep(SLEEP_TIME)
    print('               /        *      \                 ')
    sleep(SLEEP_TIME)
    print('              /          *      \                ')
    sleep(SLEEP_TIME)
    print('             /            *      \               ')
    sleep(SLEEP_TIME)
    print('             \             *     /               ')
    sleep(SLEEP_TIME)
    print('              \             *   /                ')
    sleep(SLEEP_TIME)
    print('               \             * /                 ')
    sleep(SLEEP_TIME)
    print('               /            *  \                 ')
    sleep(SLEEP_TIME)
    print('              /            *    \                ')
    sleep(SLEEP_TIME)
    print('             /            *      \               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
def chemin_2():
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /           *         \              ')
    sleep(SLEEP_TIME)
    print('           /             *         \             ')
    sleep(SLEEP_TIME)
    print('          /               *         \            ')
    sleep(SLEEP_TIME)
    print('         /                 *         \           ')
    sleep(SLEEP_TIME)
    print('        /                   *         \          ')
    sleep(SLEEP_TIME)
    print('       /                     *         \         ')
    sleep(SLEEP_TIME)
    print('      /                     *           \        ')
    sleep(SLEEP_TIME)
    print('     /                     *             \       ')
    sleep(SLEEP_TIME)
    print('    /                     *               \      ')
    sleep(SLEEP_TIME)
    print('   /                     *                 \     ')
    sleep(SLEEP_TIME)
    print('  /                     *                   \    ')
    sleep(SLEEP_TIME)
    print(' /                       *                   \   ')
    sleep(SLEEP_TIME)
    print('/                         *                   \  ')
    sleep(SLEEP_TIME)
    print('\                          *                  /  ')
    sleep(SLEEP_TIME)
    print(' \                        *                  /   ')
    sleep(SLEEP_TIME)
    print('  \                      *                  /    ')
    sleep(SLEEP_TIME)
    print('   \                    *                  /     ')
    sleep(SLEEP_TIME)
    print('    \                  *                  /      ')
    sleep(SLEEP_TIME)
    print('     \                *                  /       ')
    sleep(SLEEP_TIME)
    print('      \              *                  /        ')
    sleep(SLEEP_TIME)
    print('       \            *                  /         ')
    sleep(SLEEP_TIME)
    print('        \          *                  /          ')
    sleep(SLEEP_TIME)
    print('         \          *                /           ')
    sleep(SLEEP_TIME)
    print('          \          *              /            ')
    sleep(SLEEP_TIME)
    print('           \          *            /             ')
    sleep(SLEEP_TIME)
    print('            \          *          /              ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \          *      /                ')
    sleep(SLEEP_TIME)
    print('               \          *    /                 ')
    sleep(SLEEP_TIME)
    print('                \          *  /                  ')
    sleep(SLEEP_TIME)
    print('                 \          */                   ')
    sleep(SLEEP_TIME)
    print('                  \       * /                    ')
    sleep(SLEEP_TIME)
    print('                   \     * /                     ')
    sleep(SLEEP_TIME)
    print('                    \   * /                      ')
    sleep(SLEEP_TIME)
    print('                     \ * /                       ')
    sleep(SLEEP_TIME)
    print('                     |*  |                       ')
    sleep(SLEEP_TIME)
    print('                     |  *|                       ')
    sleep(SLEEP_TIME)
    print('                     /*  \                       ')
    sleep(SLEEP_TIME)
    print('                    /   * \                      ')
    sleep(SLEEP_TIME)
    print('                   /   *   \                     ')
    sleep(SLEEP_TIME)
    print('                  /   *     \                    ')
    sleep(SLEEP_TIME)
    print('                 /     *     \                   ')
    sleep(SLEEP_TIME)
    print('                /       *     \                  ')
    sleep(SLEEP_TIME)
    print('               /         *     \                 ')
    sleep(SLEEP_TIME)
    print('              /          *      \                ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
def chemin_3():
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('            /           *       /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /           *       /                   ')
    sleep(SLEEP_TIME)
    print('        /           *       /                    ')
    sleep(SLEEP_TIME)
    print('        \            *      \                    ')
    sleep(SLEEP_TIME)
    print('         \            *      \                   ')
    sleep(SLEEP_TIME)
    print('          \            *      \                  ')
    sleep(SLEEP_TIME)
    print('           \            *      \                 ')
    sleep(SLEEP_TIME)
    print('            \            *      \                ')
    sleep(SLEEP_TIME)
    print('             \            *      \               ')
    sleep(SLEEP_TIME)
    print('             /           *       /               ')
    sleep(SLEEP_TIME)
    print('            /           *       /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /           *       /                   ')
    sleep(SLEEP_TIME)
    print('         \            *      \                   ')
    sleep(SLEEP_TIME)
    print('          \            *      \                  ')
    sleep(SLEEP_TIME)
    print('           \            *      \                 ')
    sleep(SLEEP_TIME)
    print('            \            *      \                ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
def chemin_4():
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
def chemin_5():
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |            *      |               ')
    sleep(SLEEP_TIME)
    print('             |             *     |               ')
    sleep(SLEEP_TIME)
    print('             |              *    |               ')
    sleep(SLEEP_TIME)
    print('             |               *   |               ')
    sleep(SLEEP_TIME)
    print('             |                *  |               ')
    sleep(SLEEP_TIME)
    print('             |                 * |               ')
    sleep(SLEEP_TIME)
    print('             \                *  /               ')
    sleep(SLEEP_TIME)
    print('              \              *  /                ')
    sleep(SLEEP_TIME)
    print('               \            *  /                 ')
    sleep(SLEEP_TIME)
    print('               /           *   \                 ')
    sleep(SLEEP_TIME)
    print('              /           *     \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /     *         \                 ')
    sleep(SLEEP_TIME)
    print('              /     *           \                ')
    sleep(SLEEP_TIME)
    print('             /     *             \               ')
    sleep(SLEEP_TIME)
    print('             \    *              /               ')
    sleep(SLEEP_TIME)
    print('              \  *              /                ')
    sleep(SLEEP_TIME)
    print('               \*              /                 ')
    sleep(SLEEP_TIME)
    print('               / *             \                 ')
    sleep(SLEEP_TIME)
    print('              /   *             \                ')
    sleep(SLEEP_TIME)
    print('             /     *             \               ')
    sleep(SLEEP_TIME)
    print('             \      *            /               ')
    sleep(SLEEP_TIME)
    print('              \      *          /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /          *        \               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
def chemin_6():
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /           *         \              ')
    sleep(SLEEP_TIME)
    print('           /           *           \             ')
    sleep(SLEEP_TIME)
    print('          /           *             \            ')
    sleep(SLEEP_TIME)
    print('         /             *             \           ')
    sleep(SLEEP_TIME)
    print('        /               *             \          ')
    sleep(SLEEP_TIME)
    print('       /                 *             \         ')
    sleep(SLEEP_TIME)
    print('      /                 *               \        ')
    sleep(SLEEP_TIME)
    print('     /                 *                \       ')
    sleep(SLEEP_TIME)
    print('    /                   *                 \      ')
    sleep(SLEEP_TIME)
    print('   /                     *                 \     ')
    sleep(SLEEP_TIME)
    print('  /                       *                 \    ')
    sleep(SLEEP_TIME)
    print(' /                       *                   \   ')
    sleep(SLEEP_TIME)
    print('/                       *                     \  ')
    sleep(SLEEP_TIME)
    print('\                      *                      /  ')
    sleep(SLEEP_TIME)
    print(' \                      *                    /   ')
    sleep(SLEEP_TIME)
    print('  \                      *                  /    ')
    sleep(SLEEP_TIME)
    print('   \                      *                /     ')
    sleep(SLEEP_TIME)
    print('    \                    *                /      ')
    sleep(SLEEP_TIME)
    print('     \                  *                /       ')
    sleep(SLEEP_TIME)
    print('      \                *                /        ')
    sleep(SLEEP_TIME)
    print('       \                *              /         ')
    sleep(SLEEP_TIME)
    print('        \                *            /          ')
    sleep(SLEEP_TIME)
    print('         \                *          /           ')
    sleep(SLEEP_TIME)
    print('          \              *          /            ')
    sleep(SLEEP_TIME)
    print('           \            *          /             ')
    sleep(SLEEP_TIME)
    print('            \          *          /              ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \          *      /                ')
    sleep(SLEEP_TIME)
    print('               \          *    /                 ')
    sleep(SLEEP_TIME)
    print('                \        *    /                  ')
    sleep(SLEEP_TIME)
    print('                 \      *    /                   ')
    sleep(SLEEP_TIME)
    print('                  \    *    /                    ')
    sleep(SLEEP_TIME)
    print('                   \  *    /                     ')
    sleep(SLEEP_TIME)
    print('                    \*    /                      ')
    sleep(SLEEP_TIME)
    print('                     \*  /                       ')
    sleep(SLEEP_TIME)
    print('                     | * |                       ')
    sleep(SLEEP_TIME)
    print('                     |  *|                       ')
    sleep(SLEEP_TIME)
    print('                     / * \                       ')
    sleep(SLEEP_TIME)
    print('                    / *   \                      ')
    sleep(SLEEP_TIME)
    print('                   / *     \                     ')
    sleep(SLEEP_TIME)
    print('                  / *       \                    ')
    sleep(SLEEP_TIME)
    print('                 /   *       \                   ')
    sleep(SLEEP_TIME)
    print('                /     *       \                  ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
def chemin_7():
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /          *          \              ')
    sleep(SLEEP_TIME)
    print('           /          *            \             ')
    sleep(SLEEP_TIME)
    print('          /          *              \            ')
    sleep(SLEEP_TIME)
    print('         /          *                \           ')
    sleep(SLEEP_TIME)
    print('        /          *                  \          ')
    sleep(SLEEP_TIME)
    print('       /          *                    \         ')
    sleep(SLEEP_TIME)
    print('      /            *                    \        ')
    sleep(SLEEP_TIME)
    print('     /              *                    \       ')
    sleep(SLEEP_TIME)
    print('    /                *                    \      ')
    sleep(SLEEP_TIME)
    print('   /                  *                    \     ')
    sleep(SLEEP_TIME)
    print('  /                    *                    \    ')
    sleep(SLEEP_TIME)
    print(' /                      *                    \   ')
    sleep(SLEEP_TIME)
    print('/                      *                      \  ')
    sleep(SLEEP_TIME)
    print('\                     *                       /  ')
    sleep(SLEEP_TIME)
    print(' \                   *                       /   ')
    sleep(SLEEP_TIME)
    print('  \                 *                       /    ')
    sleep(SLEEP_TIME)
    print('   \               *                       /     ')
    sleep(SLEEP_TIME)
    print('    \             *                       /      ')
    sleep(SLEEP_TIME)
    print('     \             *                     /       ')
    sleep(SLEEP_TIME)
    print('      \             *                   /        ')
    sleep(SLEEP_TIME)
    print('       \             *                 /         ')
    sleep(SLEEP_TIME)
    print('        \             *               /          ')
    sleep(SLEEP_TIME)
    print('         \             *             /           ')
    sleep(SLEEP_TIME)
    print('          \             *           /            ')
    sleep(SLEEP_TIME)
    print('           \             *         /             ')
    sleep(SLEEP_TIME)
    print('            \           *         /              ')
    sleep(SLEEP_TIME)
    print('             \         *         /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \       *       /                 ')
    sleep(SLEEP_TIME)
    print('                \      *      /                  ')
    sleep(SLEEP_TIME)
    print('                 \     *     /                   ')
    sleep(SLEEP_TIME)
    print('                  \    *    /                    ')
    sleep(SLEEP_TIME)
    print('                   \   *   /                     ')
    sleep(SLEEP_TIME)
    print('                    \  *  /                      ')
    sleep(SLEEP_TIME)
    print('                     \ * /                       ')
    sleep(SLEEP_TIME)
    print('                     | * |                       ')
    sleep(SLEEP_TIME)
    print('                     | * |                       ')
    sleep(SLEEP_TIME)
    print('                     / * \                       ')
    sleep(SLEEP_TIME)
    print('                    /  *  \                      ')
    sleep(SLEEP_TIME)
    print('                   /   *   \                     ')
    sleep(SLEEP_TIME)
    print('                  /    *    \                    ')
    sleep(SLEEP_TIME)
    print('                 /     *     \                   ')
    sleep(SLEEP_TIME)
    print('                /      *      \                  ')
    sleep(SLEEP_TIME)
    print('               /      *        \                 ')
    sleep(SLEEP_TIME)
    print('              /      *          \                ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
def chemin_8():
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /           *       /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /           *       /                   ')
    sleep(SLEEP_TIME)
    print('        /           *       /                    ')
    sleep(SLEEP_TIME)
    print('        \          *        \                    ')
    sleep(SLEEP_TIME)
    print('         \        *          \                   ')
    sleep(SLEEP_TIME)
    print('          \      *            \                  ')
    sleep(SLEEP_TIME)
    print('           \    *              \                 ')
    sleep(SLEEP_TIME)
    print('            \  *                \                ')
    sleep(SLEEP_TIME)
    print('             \*                  \               ')
    sleep(SLEEP_TIME)
    print('             / *                 /               ')
    sleep(SLEEP_TIME)
    print('            /   *               /                ')
    sleep(SLEEP_TIME)
    print('           /     *             /                 ')
    sleep(SLEEP_TIME)
    print('          /       *           /                  ')
    sleep(SLEEP_TIME)
    print('         /         *         /                   ')
    sleep(SLEEP_TIME)
    print('         \          *        \                   ')
    sleep(SLEEP_TIME)
    print('          \         *         \                  ')
    sleep(SLEEP_TIME)
    print('           \         *         \                 ')
    sleep(SLEEP_TIME)
    print('            \         *         \                ')
    sleep(SLEEP_TIME)
    print('             |         *        |               ')
    sleep(SLEEP_TIME)
def chemin_9():
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('            /          *        /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /            *      /                   ')
    sleep(SLEEP_TIME)
    print('        /             *     /                    ')
    sleep(SLEEP_TIME)
    print('        \            *      \                    ')
    sleep(SLEEP_TIME)
    print('         \           *       \                   ')
    sleep(SLEEP_TIME)
    print('          \          *        \                  ')
    sleep(SLEEP_TIME)
    print('           \        *          \                 ')
    sleep(SLEEP_TIME)
    print('            \       *           \                ')
    sleep(SLEEP_TIME)
    print('             \      *            \               ')
    sleep(SLEEP_TIME)
    print('             /     *             /               ')
    sleep(SLEEP_TIME)
    print('            /      *            /                ')
    sleep(SLEEP_TIME)
    print('           /       *           /                 ')
    sleep(SLEEP_TIME)
    print('          /         *         /                  ')
    sleep(SLEEP_TIME)
    print('         /          *        /                   ')
    sleep(SLEEP_TIME)
    print('         \          *        \                   ')
    sleep(SLEEP_TIME)
    print('         |           *        |                  ')
    sleep(SLEEP_TIME)
for i in range(2):
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |        *          |               ')
    sleep(SLEEP_TIME)
    print('             |       *           |               ')
    sleep(SLEEP_TIME)
    print('             |      *            |               ')
    sleep(SLEEP_TIME)
    print('             |     *             |               ')
    sleep(SLEEP_TIME)
    print('             |      *            |               ')
    sleep(SLEEP_TIME)
    print('             |       *           |               ')
    sleep(SLEEP_TIME)
    print('             \        *          /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /     *         \                 ')
    sleep(SLEEP_TIME)
    print('              /     *           \                ')
    sleep(SLEEP_TIME)
    print('             /     *             \               ')
    sleep(SLEEP_TIME)
    print('             \    *              /               ')
    sleep(SLEEP_TIME)
    print('              \  *              /                ')
    sleep(SLEEP_TIME)
    print('               \*              /                 ')
    sleep(SLEEP_TIME)
    print('               /  *            \                 ')
    sleep(SLEEP_TIME)
    print('              /    *            \                ')
    sleep(SLEEP_TIME)
    print('             /      *            \               ')
    sleep(SLEEP_TIME)
    print('             \       *           /               ')
    sleep(SLEEP_TIME)
    print('              \       *         /                ')
    sleep(SLEEP_TIME)
    print('               \       *       /                 ')
    sleep(SLEEP_TIME)
    print('               /        *      \                 ')
    sleep(SLEEP_TIME)
    print('              /          *      \                ')
    sleep(SLEEP_TIME)
    print('             /            *      \               ')
    sleep(SLEEP_TIME)
    print('             \             *     /               ')
    sleep(SLEEP_TIME)
    print('              \             *   /                ')
    sleep(SLEEP_TIME)
    print('               \             * /                 ')
    sleep(SLEEP_TIME)
    print('               /            *  \                 ')
    sleep(SLEEP_TIME)
    print('              /            *    \                ')
    sleep(SLEEP_TIME)
    print('             /            *      \               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /           *         \              ')
    sleep(SLEEP_TIME)
    print('           /             *         \             ')
    sleep(SLEEP_TIME)
    print('          /               *         \            ')
    sleep(SLEEP_TIME)
    print('         /                 *         \           ')
    sleep(SLEEP_TIME)
    print('        /                   *         \          ')
    sleep(SLEEP_TIME)
    print('       /                     *         \         ')
    sleep(SLEEP_TIME)
    print('      /                     *           \        ')
    sleep(SLEEP_TIME)
    print('     /                     *             \       ')
    sleep(SLEEP_TIME)
    print('    /                     *               \      ')
    sleep(SLEEP_TIME)
    print('   /                     *                 \     ')
    sleep(SLEEP_TIME)
    print('  /                     *                   \    ')
    sleep(SLEEP_TIME)
    print(' /                       *                   \   ')
    sleep(SLEEP_TIME)
    print('/                         *                   \  ')
    sleep(SLEEP_TIME)
    print('\                          *                  /  ')
    sleep(SLEEP_TIME)
    print(' \                        *                  /   ')
    sleep(SLEEP_TIME)
    print('  \                      *                  /    ')
    sleep(SLEEP_TIME)
    print('   \                    *                  /     ')
    sleep(SLEEP_TIME)
    print('    \                  *                  /      ')
    sleep(SLEEP_TIME)
    print('     \                *                  /       ')
    sleep(SLEEP_TIME)
    print('      \              *                  /        ')
    sleep(SLEEP_TIME)
    print('       \            *                  /         ')
    sleep(SLEEP_TIME)
    print('        \          *                  /          ')
    sleep(SLEEP_TIME)
    print('         \          *                /           ')
    sleep(SLEEP_TIME)
    print('          \          *              /            ')
    sleep(SLEEP_TIME)
    print('           \          *            /             ')
    sleep(SLEEP_TIME)
    print('            \          *          /              ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \          *      /                ')
    sleep(SLEEP_TIME)
    print('               \          *    /                 ')
    sleep(SLEEP_TIME)
    print('                \          *  /                  ')
    sleep(SLEEP_TIME)
    print('                 \          */                   ')
    sleep(SLEEP_TIME)
    print('                  \       * /                    ')
    sleep(SLEEP_TIME)
    print('                   \     * /                     ')
    sleep(SLEEP_TIME)
    print('                    \   * /                      ')
    sleep(SLEEP_TIME)
    print('                     \ * /                       ')
    sleep(SLEEP_TIME)
    print('                     |*  |                       ')
    sleep(SLEEP_TIME)
    print('                     |  *|                       ')
    sleep(SLEEP_TIME)
    print('                     /*  \                       ')
    sleep(SLEEP_TIME)
    print('                    /   * \                      ')
    sleep(SLEEP_TIME)
    print('                   /   *   \                     ')
    sleep(SLEEP_TIME)
    print('                  /   *     \                    ')
    sleep(SLEEP_TIME)
    print('                 /     *     \                   ')
    sleep(SLEEP_TIME)
    print('                /       *     \                  ')
    sleep(SLEEP_TIME)
    print('               /         *     \                 ')
    sleep(SLEEP_TIME)
    print('              /          *      \                ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('            /           *       /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /           *       /                   ')
    sleep(SLEEP_TIME)
    print('        /           *       /                    ')
    sleep(SLEEP_TIME)
    print('        \            *      \                    ')
    sleep(SLEEP_TIME)
    print('         \            *      \                   ')
    sleep(SLEEP_TIME)
    print('          \            *      \                  ')
    sleep(SLEEP_TIME)
    print('           \            *      \                 ')
    sleep(SLEEP_TIME)
    print('            \            *      \                ')
    sleep(SLEEP_TIME)
    print('             \            *      \               ')
    sleep(SLEEP_TIME)
    print('             /           *       /               ')
    sleep(SLEEP_TIME)
    print('            /           *       /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /           *       /                   ')
    sleep(SLEEP_TIME)
    print('         \            *      \                   ')
    sleep(SLEEP_TIME)
    print('          \            *      \                  ')
    sleep(SLEEP_TIME)
    print('           \            *      \                 ')
    sleep(SLEEP_TIME)
    print('            \            *      \                ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             |           *       |               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \      *        /                 ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             /           *       \               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /           *         \              ')
    sleep(SLEEP_TIME)
    print('           /           *           \             ')
    sleep(SLEEP_TIME)
    print('          /           *             \            ')
    sleep(SLEEP_TIME)
    print('         /             *             \           ')
    sleep(SLEEP_TIME)
    print('        /               *             \          ')
    sleep(SLEEP_TIME)
    print('       /                 *             \         ')
    sleep(SLEEP_TIME)
    print('      /                 *               \        ')
    sleep(SLEEP_TIME)
    print('     /                 *                \       ')
    sleep(SLEEP_TIME)
    print('    /                   *                 \      ')
    sleep(SLEEP_TIME)
    print('   /                     *                 \     ')
    sleep(SLEEP_TIME)
    print('  /                       *                 \    ')
    sleep(SLEEP_TIME)
    print(' /                       *                   \   ')
    sleep(SLEEP_TIME)
    print('/                       *                     \  ')
    sleep(SLEEP_TIME)
    print('\                      *                      /  ')
    sleep(SLEEP_TIME)
    print(' \                      *                    /   ')
    sleep(SLEEP_TIME)
    print('  \                      *                  /    ')
    sleep(SLEEP_TIME)
    print('   \                      *                /     ')
    sleep(SLEEP_TIME)
    print('    \                    *                /      ')
    sleep(SLEEP_TIME)
    print('     \                  *                /       ')
    sleep(SLEEP_TIME)
    print('      \                *                /        ')
    sleep(SLEEP_TIME)
    print('       \                *              /         ')
    sleep(SLEEP_TIME)
    print('        \                *            /          ')
    sleep(SLEEP_TIME)
    print('         \                *          /           ')
    sleep(SLEEP_TIME)
    print('          \              *          /            ')
    sleep(SLEEP_TIME)
    print('           \            *          /             ')
    sleep(SLEEP_TIME)
    print('            \          *          /              ')
    sleep(SLEEP_TIME)
    print('             \          *        /               ')
    sleep(SLEEP_TIME)
    print('              \          *      /                ')
    sleep(SLEEP_TIME)
    print('               \          *    /                 ')
    sleep(SLEEP_TIME)
    print('                \        *    /                  ')
    sleep(SLEEP_TIME)
    print('                 \      *    /                   ')
    sleep(SLEEP_TIME)
    print('                  \    *    /                    ')
    sleep(SLEEP_TIME)
    print('                   \  *    /                     ')
    sleep(SLEEP_TIME)
    print('                    \*    /                      ')
    sleep(SLEEP_TIME)
    print('                     \*  /                       ')
    sleep(SLEEP_TIME)
    print('                     | * |                       ')
    sleep(SLEEP_TIME)
    print('                     |  *|                       ')
    sleep(SLEEP_TIME)
    print('                     / * \                       ')
    sleep(SLEEP_TIME)
    print('                    / *   \                      ')
    sleep(SLEEP_TIME)
    print('                   / *     \                     ')
    sleep(SLEEP_TIME)
    print('                  / *       \                    ')
    sleep(SLEEP_TIME)
    print('                 /   *       \                   ')
    sleep(SLEEP_TIME)
    print('                /     *       \                  ')
    sleep(SLEEP_TIME)
    print('               /       *       \                 ')
    sleep(SLEEP_TIME)
    print('              /         *       \                ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('            /          *          \              ')
    sleep(SLEEP_TIME)
    print('           /          *            \             ')
    sleep(SLEEP_TIME)
    print('          /          *              \            ')
    sleep(SLEEP_TIME)
    print('         /          *                \           ')
    sleep(SLEEP_TIME)
    print('        /          *                  \          ')
    sleep(SLEEP_TIME)
    print('       /          *                    \         ')
    sleep(SLEEP_TIME)
    print('      /            *                    \        ')
    sleep(SLEEP_TIME)
    print('     /              *                    \       ')
    sleep(SLEEP_TIME)
    print('    /                *                    \      ')
    sleep(SLEEP_TIME)
    print('   /                  *                    \     ')
    sleep(SLEEP_TIME)
    print('  /                    *                    \    ')
    sleep(SLEEP_TIME)
    print(' /                      *                    \   ')
    sleep(SLEEP_TIME)
    print('/                      *                      \  ')
    sleep(SLEEP_TIME)
    print('\                     *                       /  ')
    sleep(SLEEP_TIME)
    print(' \                   *                       /   ')
    sleep(SLEEP_TIME)
    print('  \                 *                       /    ')
    sleep(SLEEP_TIME)
    print('   \               *                       /     ')
    sleep(SLEEP_TIME)
    print('    \             *                       /      ')
    sleep(SLEEP_TIME)
    print('     \             *                     /       ')
    sleep(SLEEP_TIME)
    print('      \             *                   /        ')
    sleep(SLEEP_TIME)
    print('       \             *                 /         ')
    sleep(SLEEP_TIME)
    print('        \             *               /          ')
    sleep(SLEEP_TIME)
    print('         \             *             /           ')
    sleep(SLEEP_TIME)
    print('          \             *           /            ')
    sleep(SLEEP_TIME)
    print('           \             *         /             ')
    sleep(SLEEP_TIME)
    print('            \           *         /              ')
    sleep(SLEEP_TIME)
    print('             \         *         /               ')
    sleep(SLEEP_TIME)
    print('              \        *        /                ')
    sleep(SLEEP_TIME)
    print('               \       *       /                 ')
    sleep(SLEEP_TIME)
    print('                \      *      /                  ')
    sleep(SLEEP_TIME)
    print('                 \     *     /                   ')
    sleep(SLEEP_TIME)
    print('                  \    *    /                    ')
    sleep(SLEEP_TIME)
    print('                   \   *   /                     ')
    sleep(SLEEP_TIME)
    print('                    \  *  /                      ')
    sleep(SLEEP_TIME)
    print('                     \ * /                       ')
    sleep(SLEEP_TIME)
    print('                     | * |                       ')
    sleep(SLEEP_TIME)
    print('                     | * |                       ')
    sleep(SLEEP_TIME)
    print('                     / * \                       ')
    sleep(SLEEP_TIME)
    print('                    /  *  \                      ')
    sleep(SLEEP_TIME)
    print('                   /   *   \                     ')
    sleep(SLEEP_TIME)
    print('                  /    *    \                    ')
    sleep(SLEEP_TIME)
    print('                 /     *     \                   ')
    sleep(SLEEP_TIME)
    print('                /      *      \                  ')
    sleep(SLEEP_TIME)
    print('               /      *        \                 ')
    sleep(SLEEP_TIME)
    print('              /      *          \                ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('             |          *        |               ')
    sleep(SLEEP_TIME)
    print('             |         *         |               ')
    sleep(SLEEP_TIME)
    print('            /          *        /                ')
    sleep(SLEEP_TIME)
    print('           /           *       /                 ')
    sleep(SLEEP_TIME)
    print('          /           *       /                  ')
    sleep(SLEEP_TIME)
    print('         /            *      /                   ')
    sleep(SLEEP_TIME)
    print('        /             *     /                    ')
    sleep(SLEEP_TIME)
    print('        \            *      \                    ')
    sleep(SLEEP_TIME)
    print('         \           *       \                   ')
    sleep(SLEEP_TIME)
    print('          \          *        \                  ')
    sleep(SLEEP_TIME)
    print('           \        *          \                 ')
    sleep(SLEEP_TIME)
    print('            \       *           \                ')
    sleep(SLEEP_TIME)
    print('             \      *            \               ')
    sleep(SLEEP_TIME)
    print('             /     *             /               ')
    sleep(SLEEP_TIME)
    print('            /      *            /                ')
    sleep(SLEEP_TIME)
    print('           /       *           /                 ')
    sleep(SLEEP_TIME)
    print('          /         *         /                  ')
    sleep(SLEEP_TIME)
    print('         /          *        /                   ')
    sleep(SLEEP_TIME)
    print('         \          *        \                   ')
    sleep(SLEEP_TIME)
    print('         |           *        |                  ')
    sleep(SLEEP_TIME)
print("C'était beau hein ??")